---


- name: Configuring Logging on IOS devices
  hosts: NXOS
  gather_facts: false
  connection: local

  vars:
    cli:
      username: cisco
      password: cisco 
      timeout: 100 
  
  tasks:
    - name: NXOS TIME BABY
      nxos_command:
        provider: "{{cli}}"
        commands: 
          - configure terminal
          - hostname {{hostname.name}}
