---


- name: MSDP-LAB
  hosts: NXOS
  connection: local
  gather_facts: false
  
  tasks:
    - name: configuring the interfaces  
      nxos_config:
        timeout: 150  
        src: bgp_builder.j2
