---


- name: MSDP-LAB
  hosts: NXOS
  connection: local
  gather_facts: false
  
  tasks:
    - name: applying base services and configuration 
      nxos_config:
        timeout: 150
        src: services.j2

    - name: configuring interfaces and routing 
      nxos_config:
        timeout: 150
        src: interfaces.j2
