---


- name: MSDP-LAB
  gather_facts: false
  hosts: NXOS10
  connection: local

  tasks:
    - name: Template a file to /etc/files.conf
      template:
        src: interfaces.j2
        dest: TemplateResult
