---


- name: MSDP-LAB
  gather_facts: false
  hosts: NXOS
  connection: local

  tasks:
    - name: Template a file to /etc/files.conf
      template:
        src: bgp_builder.j2
        dest: TemplateResult
